/**
 * legacy CSS 构建管线：
 *   1. sync-theme 生成 v3 config + :root 变量块
 *   2. 预处理 globals.css（剥离 v4 专属指令），拼接 v3 三段指令 + 共享 base
 *   3. Tailwind v3 CLI 编译
 *   4. PostCSS：strip-layers / oklab→rgb / preset-env / autoprefixer
 *   5. 输出 public/legacy/legacy.<hash>.css + detect.<hash>.js + generated/legacy-css.ts
 *
 * 用法：pnpm --filter @tzj/legacy-css build
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import oklabFunction from '@csstools/postcss-oklab-function';
import autoprefixer from 'autoprefixer';
import postcss from 'postcss';
import postcssPresetEnv from 'postcss-preset-env';
import { generate } from './scripts/sync-theme.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = here;
const repoRoot = path.resolve(here, '../..');
const tmpDir = path.join(pkgRoot, '.tmp');

const UI_CSS = path.join(repoRoot, 'packages/ui/src/globals.css');
const WEB_CSS = path.join(repoRoot, 'apps/web/src/app/globals.css');
const LEGACY_DIR = path.join(repoRoot, 'apps/web/public/legacy');
const GENERATED_TS = path.join(repoRoot, 'apps/web/src/generated/legacy-css.ts');
const TAILWIND_BIN = path.join(pkgRoot, 'node_modules/.bin/tailwindcss');

function removeAtRuleBlock(css, name) {
  let out = css;
  let start = out.indexOf(`@${name}`);
  while (start >= 0) {
    const brace = out.indexOf('{', start);
    if (brace < 0) break;
    let depth = 0;
    let end = -1;
    for (let i = brace; i < out.length; i++) {
      if (out[i] === '{') depth++;
      else if (out[i] === '}') {
        depth--;
        if (depth === 0) {
          end = i + 1;
          break;
        }
      }
    }
    if (end < 0) break;
    out = out.slice(0, start) + out.slice(end);
    const next = out.indexOf(`@${name}`);
    if (next === start) break;
    start = next;
  }
  return out;
}

function transformUiCss(css) {
  let out = css.replace('@import "tailwindcss";', '');
  out = removeAtRuleBlock(out, 'theme');
  return out;
}

function transformWebCss(css) {
  let out = css.replace(
    '@import "tailwindcss";',
    '@tailwind base;\n@tailwind components;\n@tailwind utilities;',
  );
  out = out
    .split('\n')
    .filter((line) => {
      const t = line.trim();
      return !(
        t.startsWith('@import') ||
        t.startsWith('@source') ||
        t.startsWith('@custom-variant')
      );
    })
    .join('\n');
  out = removeAtRuleBlock(out, 'theme inline');
  return out;
}

function stripLegacyLayersPlugin() {
  return {
    postcssPlugin: 'strip-legacy-layers',
    Once(root) {
      root.walkAtRules((atRule) => {
        if (atRule.name === 'layer') {
          atRule.replaceWith(...atRule.nodes);
        } else if (atRule.name === 'property') {
          const name = atRule.params.trim();
          let initial = null;
          atRule.walkDecls((decl) => {
            if (decl.prop === 'initial-value') initial = decl.value;
          });
          if (name.startsWith('--') && initial) {
            const rootRule = postcss.rule({ selector: ':root' });
            rootRule.append({ prop: name, value: initial });
            atRule.replaceWith(rootRule);
          } else {
            atRule.remove();
          }
        }
      });
    },
  };
}

function detectJs(href) {
  const rawPercent = Number(process.env.LEGACY_CSS_PERCENT ?? '100');
  const percent = Number.isFinite(rawPercent)
    ? Math.min(100, Math.max(0, Math.floor(rawPercent)))
    : 100;
  return `/* GENERATED by packages/legacy-css/build.mjs — 请勿手改 */
(function () {
  function uaBucket() {
    var s = (navigator.userAgent || '').toLowerCase();
    var h = 0;
    for (var i = 0; i < s.length; i++) {
      h = (h * 31 + s.charCodeAt(i)) >>> 0;
    }
    return h % 100;
  }
  var ok = false;
  try {
    ok =
      CSS.supports('color', 'oklch(50% 0.15 100)') &&
      CSS.supports('color', 'color-mix(in srgb, red 50%, blue)');
  } catch (e) {
    ok = false;
  }
  var injected = '0';
  if (!ok && !document.querySelector('link[data-track="legacy"]') && uaBucket() < ${percent}) {
    try {
      var l = document.createElement('link');
      l.rel = 'stylesheet';
      l.href = '${href}';
      l.setAttribute('data-track', 'legacy');
      l.onerror = function () {
        document.documentElement.setAttribute('data-css-track', 'legacy-error');
      };
      document.head.appendChild(l);
      injected = '1';
    } catch (e) {}
  }
  try {
    document.documentElement.setAttribute('data-css-track', ok ? 'modern' : 'legacy');
    document.documentElement.setAttribute('data-css-injected', injected);
  } catch (e) {}
})();
`;
}

function cleanupOldArtifacts(currentFiles) {
  if (!fs.existsSync(LEGACY_DIR)) return;
  for (const name of fs.readdirSync(LEGACY_DIR)) {
    if (currentFiles.has(name)) continue;
    if (/^(legacy|detect)\.[0-9a-f]+\.(css|js|css\.map)$/.test(name)) {
      fs.unlinkSync(path.join(LEGACY_DIR, name));
    }
  }
}

async function main() {
  const stats = generate();
  console.log(`[build] theme: colors=${stats.colors} radius=${stats.radius} fonts=${stats.fonts}`);

  fs.mkdirSync(tmpDir, { recursive: true });
  fs.mkdirSync(LEGACY_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(GENERATED_TS), { recursive: true });

  const uiCss = transformUiCss(fs.readFileSync(UI_CSS, 'utf8'));
  const webCss = transformWebCss(fs.readFileSync(WEB_CSS, 'utf8'));
  const themeCss = fs.readFileSync(path.join(pkgRoot, 'legacy-theme.css'), 'utf8');

  const combined = webCss.replace(
    '@tailwind utilities;',
    `@tailwind utilities;\n${uiCss}\n${themeCss}`,
  );
  const inputPath = path.join(tmpDir, 'input.css');
  const intermediatePath = path.join(tmpDir, 'intermediate.css');
  fs.writeFileSync(inputPath, combined);

  console.log('[build] tailwind v3 compile...');
  execFileSync(
    TAILWIND_BIN,
    ['-c', path.join(pkgRoot, 'tailwind.config.cjs'), '-i', inputPath, '-o', intermediatePath],
    { stdio: 'inherit' },
  );

  const intermediate = fs.readFileSync(intermediatePath, 'utf8');
  const result = await postcss([
    stripLegacyLayersPlugin(),
    oklabFunction(),
    postcssPresetEnv({
      browsers: ['chrome >= 88', 'android >= 88', 'safari >= 14'],
      stage: 3,
    }),
    autoprefixer({ overrideBrowserslist: ['chrome >= 88', 'android >= 88', 'safari >= 14'] }),
  ]).process(intermediate, { from: intermediatePath, to: path.join(tmpDir, 'legacy.css') });

  const css = result.css;
  const hash = createHash('sha256').update(css).digest('hex').slice(0, 12);
  const legacyFile = `legacy.${hash}.css`;
  const detectFile = `detect.${hash}.js`;
  const legacyPath = path.join(LEGACY_DIR, legacyFile);
  const detectPath = path.join(LEGACY_DIR, detectFile);

  fs.writeFileSync(legacyPath, css);
  fs.writeFileSync(detectPath, detectJs(`/legacy/${legacyFile}`));
  fs.writeFileSync(
    GENERATED_TS,
    `// GENERATED by packages/legacy-css/build.mjs — 请勿手改（CI 校验见 legacy:theme:check）
export const legacyCssHref = '/legacy/${legacyFile}';
export const legacyDetectJsHref = '/legacy/${detectFile}';
`,
  );

  cleanupOldArtifacts(new Set([legacyFile, detectFile]));
  fs.rmSync(tmpDir, { recursive: true, force: true });

  console.log(`[build] done: ${legacyPath} (${Buffer.byteLength(css)} bytes)`);
  console.log(`[build] detect: ${detectPath}`);
  console.log(`[build] generated: ${GENERATED_TS}`);
}

main().catch((err) => {
  console.error('[build] legacy CSS 构建失败:', err);
  process.exit(1);
});
