packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@alicloud/openapi-core': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react@1.22.0
  - postcss@8.5.16
