import { z } from "zod";
import type { ResourceConfig } from "@/components/crud/config";
import type { TradeShowItem } from "@/features/types";
import { contentAuditColumns } from "@/components/LastOperatorCell";
import {
  TRADE_SHOW_TYPE_OPTIONS,
  StatusBadge,
  formatDate,
  labelOf,
  toDateTimeLocal,
} from "@/features/constants";

const schema = z.object({
  title: z.string().min(1, "请输入名称"),
  slug: z.string().min(1, "请填写名称"),
  eventType: z.string().min(1, "请选择类型"),
  summary: z.string().optional(),
  content: z.string().optional(),
  location: z.string().optional(),
  eventDateLabel: z.string().optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  boothNumber: z.string().optional(),
  externalUrl: z.string().optional(),
  seoTitle: z.string().optional(),
  seoDesc: z.string().optional(),
  coverImage: z.string().optional(),
  isFeatured: z.boolean().optional(),
});

export const tradeShowsConfig: ResourceConfig<TradeShowItem> = {
  resource: "trade-shows",
  basePath: "/trade-shows",
  title: "展会活动",
  singular: "展会",
  searchable: true,
  filters: [{ key: "eventType", label: "全部类型", options: TRADE_SHOW_TYPE_OPTIONS }],
  columns: [
    { key: "title", header: "名称", sortable: true },
    { key: "location", header: "地点", sortable: true },
    {
      key: "eventDateLabel",
      header: "日期",
      sortable: true,
      sortKey: "startDate",
      cell: (r) => r.eventDateLabel || formatDate(r.startDate),
    },
    { key: "eventType", header: "类型", sortable: true, cell: (r) => labelOf(TRADE_SHOW_TYPE_OPTIONS, r.eventType) },
    { key: "status", header: "状态", sortable: true, cell: (r) => <StatusBadge status={r.status} /> },
    ...contentAuditColumns<TradeShowItem>(),
  ],
  fields: [
    { name: "title", label: "名称", type: "text", required: true, colSpan: 2 },
    {
      name: "eventType",
      label: "类型",
      type: "select",
      required: true,
      options: TRADE_SHOW_TYPE_OPTIONS,
    },
    { name: "location", label: "地点", type: "text" },
    {
      name: "eventDateLabel",
      label: "展示日期",
      type: "text",
      help: "可与下方精确日期并存",
    },
    { name: "startDate", label: "开始日期", type: "datetime" },
    { name: "endDate", label: "结束日期", type: "datetime" },
    { name: "boothNumber", label: "展位号", type: "text" },
    { name: "externalUrl", label: "官网链接", type: "text", colSpan: 2 },
    { name: "summary", label: "简介", type: "textarea", colSpan: 2 },
    { name: "content", label: "详情", type: "markdown", colSpan: 2, folder: "trade-shows" },
    {
      name: "coverImage",
      label: "封面图",
      type: "image",
      colSpan: 2,
      folder: "trade-shows",
      help: "建议比例 16:9",
    },
    { name: "seoTitle", label: "SEO 标题", type: "text", colSpan: 2 },
    { name: "seoDesc", label: "SEO 描述", type: "textarea", colSpan: 2 },
    { name: "isFeatured", label: "精选", type: "switch", placeholder: "设为精选" },
  ],
  schema,
  publishable: true,
  previewPath: () => "/resources/trade-shows",
  defaultSort: { column: "publishedAt", order: "desc" },
  defaults: {
    title: "",
    slug: "",
    eventType: "exhibition",
    location: "",
    eventDateLabel: "",
    startDate: "",
    endDate: "",
    boothNumber: "",
    externalUrl: "",
    summary: "",
    content: "",
    coverImage: "",
    seoTitle: "",
    seoDesc: "",
    isFeatured: false,
  },
  toForm: (r) => ({
    title: r.title,
    slug: r.slug,
    eventType: r.eventType,
    location: r.location ?? "",
    eventDateLabel: r.eventDateLabel ?? "",
    startDate: toDateTimeLocal(r.startDate),
    endDate: toDateTimeLocal(r.endDate),
    boothNumber: r.boothNumber ?? "",
    externalUrl: r.externalUrl ?? "",
    summary: r.summary ?? "",
    content: r.content ?? "",
    coverImage: r.coverImage ?? "",
    seoTitle: r.seoTitle ?? "",
    seoDesc: r.seoDesc ?? "",
    isFeatured: r.isFeatured,
  }),
};
