-- Case structured fields + SEO for all content types
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "highlights" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "specs" JSONB;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "completionDate" TIMESTAMP(3);
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "cases" ADD COLUMN IF NOT EXISTS "seoDesc" TEXT;

ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "seoDesc" TEXT;

ALTER TABLE "blogs" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "blogs" ADD COLUMN IF NOT EXISTS "seoDesc" TEXT;

ALTER TABLE "trade_shows" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "trade_shows" ADD COLUMN IF NOT EXISTS "seoDesc" TEXT;
