/**
 * 三层 token 同步：共享 @theme → web :root 覆盖 → @theme inline 映射。
 * 输出：
 *   - tailwind.config.cjs（v3 配置，oklch 已转 sRGB hex）
 *   - legacy-theme.css（:root 变量块，供 var(--color-*) 消费）
 *
 * 用法：
 *   node scripts/sync-theme.mjs          # 写回 packages/legacy-css/
 *   node scripts/sync-theme.mjs --check  # 与已提交产物比对（theme-check 内部使用）
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { converter, formatHex } from 'culori';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const repoRoot = path.resolve(pkgRoot, '../..');

const UI_CSS = path.join(repoRoot, 'packages/ui/src/globals.css');
const WEB_CSS = path.join(repoRoot, 'apps/web/src/app/globals.css');

const toRgb = converter('rgb');

function toHex(value) {
  const s = value.trim();
  if (/^#[0-9a-fA-F]{3,8}$/.test(s)) return s;
  if (/^(rgb|rgba|hsl|hsla|oklch|oklab)\(/.test(s)) {
    try {
      return formatHex(toRgb(s));
    } catch {
      return undefined;
    }
  }
  return undefined;
}

function extractBlock(css, atRule) {
  const start = css.indexOf(`@${atRule}`);
  if (start < 0) return '';
  const brace = css.indexOf('{', start);
  if (brace < 0) return '';
  let depth = 0;
  for (let i = brace; i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}') {
      depth--;
      if (depth === 0) return css.slice(start, i + 1);
    }
  }
  return '';
}

function extractRootBlock(css) {
  const start = css.indexOf(':root {');
  if (start < 0) return '';
  const brace = css.indexOf('{', start);
  if (brace < 0) return '';
  let depth = 0;
  for (let i = brace; i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}') {
      depth--;
      if (depth === 0) return css.slice(start, i + 1);
    }
  }
  return '';
}

function parseVars(block) {
  const out = {};
  for (const m of block.matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) {
    out[m[1]] = m[2].trim();
  }
  return out;
}

function resolveVar(value, vars) {
  let current = value;
  for (let i = 0; i < 5; i++) {
    const m = current.match(/^var\(--([\w-]+)\)$/);
    if (!m || !(m[1] in vars)) return current;
    current = vars[m[1]];
  }
  return current;
}

function parseFontStack(value) {
  return value
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

export function generate({ outDir = pkgRoot, check = false } = {}) {
  const uiCss = fs.readFileSync(UI_CSS, 'utf8');
  const webCss = fs.readFileSync(WEB_CSS, 'utf8');

  const uiTheme = parseVars(extractBlock(uiCss, 'theme'));
  const webRoot = parseVars(extractRootBlock(webCss));
  const webThemeInline = parseVars(extractBlock(webCss, 'theme inline'));

  // 颜色：共享 @theme 的 --color-* + web :root 的裸色名覆盖 + @theme inline 别名（解析 var 链）
  const colors = {};
  for (const [k, v] of Object.entries(uiTheme)) {
    if (!k.startsWith('color-')) continue;
    const hex = toHex(v);
    if (hex) colors[k.slice('color-'.length)] = hex;
  }
  for (const [k, v] of Object.entries(webRoot)) {
    if (k.startsWith('color-') || k.startsWith('radius-') || k.startsWith('font-')) continue;
    const hex = toHex(v);
    if (hex) colors[k] = hex;
  }
  for (const [k, v] of Object.entries(webThemeInline)) {
    if (!k.startsWith('color-')) continue;
    const resolved = resolveVar(v, webRoot);
    const hex = toHex(resolved);
    if (hex) colors[k.slice('color-'.length)] = hex;
  }

  // 圆角：共享 + web @theme inline 覆盖（web 优先）
  const borderRadius = {};
  for (const [k, v] of Object.entries({ ...uiTheme, ...webThemeInline })) {
    if (k.startsWith('radius-')) borderRadius[k.slice('radius-'.length)] = v;
  }

  const fontFamily = {};
  for (const key of ['sans', 'display']) {
    const v = webRoot[`font-${key}`];
    if (v) fontFamily[key] = parseFontStack(v);
  }

  const config = `// GENERATED by packages/legacy-css/scripts/sync-theme.mjs — 请勿手改
// 唯一事实源：packages/ui/src/globals.css @theme + apps/web/src/app/globals.css :root / @theme inline
module.exports = {
  content: [
    '${repoRoot}/apps/web/src/**/*.{ts,tsx}',
    '${repoRoot}/packages/ui/src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 2)},
      borderRadius: ${JSON.stringify(borderRadius, null, 2)},
      fontFamily: ${JSON.stringify(fontFamily, null, 2)},
    },
  },
};
`;

  const themeVars = [];
  for (const [k, v] of Object.entries(colors)) {
    themeVars.push(`  --color-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(borderRadius)) {
    themeVars.push(`  --radius-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(fontFamily)) {
    themeVars.push(`  --font-${k}: ${v.join(', ')};`);
  }
  const themeCss = `/* GENERATED by packages/legacy-css/scripts/sync-theme.mjs — 请勿手改
   v3 不自动输出 @theme 变量，此块为 var(--color-*)/var(--radius-*) 消费方提供 */
:root {
${themeVars.join('\n')}
}
`;

  const files = {
    'tailwind.config.cjs': config,
    'legacy-theme.css': themeCss,
  };

  if (check) {
    const diffs = [];
    for (const [name, content] of Object.entries(files)) {
      const file = path.join(outDir, name);
      if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) {
        diffs.push(name);
      }
    }
    return { diffs };
  }

  for (const [name, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(outDir, name), content);
  }

  return {
    colors: Object.keys(colors).length,
    radius: Object.keys(borderRadius).length,
    fonts: Object.keys(fontFamily).length,
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const stats = generate();
  console.log(
    `[sync-theme] colors=${stats.colors} radius=${stats.radius} fonts=${stats.fonts} -> ${pkgRoot}`,
  );
}
