/**
 * 全站静态路由列表 — 供 sitemap 等 SEO 工具使用
 */
export const staticRoutes = [
  { path: "/", priority: 1.0, changeFrequency: "weekly" as const },
  { path: "/contact", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/solutions", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/towers", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/fixed-tower", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/fixed-tower/series", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/fixed-tower/custom", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/fixed-tower/climbing-tower", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/education-center", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/modular-tower", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/modular-tower/series", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/modular-tower/custom", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/modular-tower/vs-containers", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/burn-rooms", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/burn-rooms/liner", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/burn-rooms/comparison", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/burn-rooms/cfbt", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/burn-rooms/fire-simulation", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/accessories", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/accessories/fitness-equipment", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/accessories/competition", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/specialized-training", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/accessories/maritime", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/accessories/tactical", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/accessories/hazmat", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/specialized-training/rope-rescue", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/specialized-training/psychological", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/cases", priority: 0.8, changeFrequency: "weekly" as const },
  { path: "/why-us", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/why-us/story", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/why-us/team", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/why-us/certification", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/why-us/global", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/resources", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/resources/how-to-buy", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/resources/design-center", priority: 0.6, changeFrequency: "monthly" as const },
  { path: "/resources/inspections", priority: 0.6, changeFrequency: "monthly" as const },
  { path: "/resources/faqs", priority: 0.6, changeFrequency: "monthly" as const },
  { path: "/resources/trade-shows", priority: 0.6, changeFrequency: "weekly" as const },
  { path: "/resources/news", priority: 0.6, changeFrequency: "weekly" as const },
  { path: "/resources/warranty", priority: 0.6, changeFrequency: "monthly" as const },
  { path: "/resources/blog", priority: 0.6, changeFrequency: "weekly" as const },
  { path: "/privacy", priority: 0.3, changeFrequency: "yearly" as const },
  { path: "/terms", priority: 0.3, changeFrequency: "yearly" as const },
] as const;
